### ISSUE TITLE
TypeError in Model DirectPredCNN: TypeError: __init__() takes from 4 to 6 positional arguments but 7 were given

### ISSUE THREAD

**Issue by kollo97** [BIMSBbioinfo/flexynesis#41]
Command:
```
flexynesis --data_path dataset1 --model_class DirectPredCNN --target_variables Erlotinib --fusion_type intermediate --hpo_iter 1 --features_min 50 --features_top_percentile 5 --log_transform False --data_types gex,cnv --outdir ./run_test1 --prefix erlotinib_direct --early_stop_patience 3 --use_loss_weighting False --evaluate_baseline_performance False
```

Returns:
```
[INFO] ================= Importing Data =================
[INFO] Validating data folders...

[INFO] ----------------- Reading Data -----------------
[INFO] Importing dataset1/train/gex.csv...
[INFO] Importing dataset1/train/clin.csv...
[INFO] Importing dataset1/train/cnv.csv...

[INFO] ----------------- Reading Data -----------------
[INFO] Importing dataset1/test/gex.csv...
[INFO] Importing dataset1/test/clin.csv...
[INFO] Importing dataset1/test/cnv.csv...

[INFO] ---------- Processing Data (train) ----------

[INFO] --------------- Cleaning Up Data ---------------
Number of NA values:  0
[INFO] DataFrame gex - Removed 0 features.
Number of NA values:  0
[INFO] DataFrame cnv - Removed 0 features.
DataFrame gex - Removed 0 samples (0.00%).
DataFrame cnv - Removed 0 samples (0.00%).
Implementing feature selection using laplacian score for layer: gex with  3422 features
Calculating Laplacian scores: 100%|████████████████████████████████████████████████████| 3422/3422 [00:00<00:00, 6529.31it/s]
Filtering redundant features: 100%|██████████████████████████████████████████████████████| 513/513 [00:00<00:00, 1499.60it/s]
Implementing feature selection using laplacian score for layer: cnv with  157 features
Calculating Laplacian scores: 100%|██████████████████████████████████████████████████████| 157/157 [00:00<00:00, 6483.33it/s]
Filtering redundant features: 100%|███████████████████████████████████████████████████████| 65/65 [00:00<00:00, 11826.73it/s]

[INFO] ---------- Processing Data (test) ----------

[INFO] --------------- Cleaning Up Data ---------------
Number of NA values:  0
[INFO] DataFrame gex - Removed 0 features.
Number of NA values:  0
[INFO] DataFrame cnv - Removed 0 features.
DataFrame gex - Removed 0 samples (0.00%).
DataFrame cnv - Removed 0 samples (0.00%).

[INFO] ------------ Harmonizing Data Sets ------------

[INFO] --------------- Normalizing Data ---------------

[INFO] --------------- Normalizing Data ---------------
[INFO] Training Data Stats:
 {'feature_count in: gex': 171, 'feature_count in: cnv': 50, 'sample_count': 920}
[INFO] Test Data Stats:
 {'feature_count in: gex': 171, 'feature_count in: cnv': 50, 'sample_count': 930}
[INFO] Data import successful.
Tuning Progress:   0%|                                                                                 | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/akollot/anaconda3/envs/flexynesis/bin/flexynesis", line 8, in <module>
    sys.exit(main())
  File "/home/akollot/projects/flexynesis_ht/flexynesis/flexynesis/__main__.py", line 99, in main
    model, best_params = tuner.perform_tuning()
  File "/home/akollot/projects/flexynesis_ht/flexynesis/flexynesis/main.py", line 114, in perform_tuning
    loss, model = self.objective(suggested_params_dict, current_step=i+1, total_steps=self.n_iter)
  File "/home/akollot/projects/flexynesis_ht/flexynesis/flexynesis/main.py", line 79, in objective
    model = self.model_class(params, self.dataset, self.target_variables, 
TypeError: __init__() takes from 4 to 6 positional arguments but 7 were given
```

**Comment by borauyar** [comment]
CNNs are not used anymore, closing the issue.
