### ISSUE TITLE
Guix installed flexynesis attempts to access user installed packages

### ISSUE THREAD

**Issue by jonasfreimuth** [BIMSBbioinfo/flexynesis#46]
Trying to run the quickstart for Guix on `flexynesis` commit [`c778eec9e3060af6bc5be00b98745998f6ecdd85`](https://github.com/BIMSBbioinfo/flexynesis/commit/c778eec9e3060af6bc5be00b98745998f6ecdd85) results in an error if there exists a `numpy` installation by the user.

Commands:

```sh
guix time-machine -C channels.scm -- shell --no-grafts -f guix.scm

# test the installation
curl -L -o dataset1.tgz https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/dataset1.tgz
tar -xzvf dataset1.tgz

flexynesis --data_path dataset1 \
  --model_class DirectPred \
  --target_variables Erlotinib \
  --fusion_type early \
  --hpo_iter 1 \
  --features_min 50 \
  --features_top_percentile 5 \
  --log_transform False \
  --data_types gex,cnv \
  --outdir . \
  --prefix erlotinib_direct \
  --early_stop_patience 3 \
  --use_loss_weighting False \
  --evaluate_baseline_performance False
```
Output:

```log
[INFO] ================= Importing Data =================
[INFO] Validating data folders...

[INFO] ----------------- Reading Data -----------------
[INFO] Importing dataset1/train/gex.csv...
[INFO] Importing dataset1/train/clin.csv...
[INFO] Importing dataset1/train/cnv.csv...

[INFO] ----------------- Reading Data -----------------
[INFO] Importing dataset1/test/gex.csv...
[INFO] Importing dataset1/test/clin.csv...
[INFO] Importing dataset1/test/cnv.csv...

[INFO] ---------- Processing Data (train) ----------

[INFO] --------------- Cleaning Up Data ---------------
Number of NA values:  0
[INFO] DataFrame gex - Removed 0 features.
Number of NA values:  0
[INFO] DataFrame cnv - Removed 0 features.
DataFrame gex - Removed 0 samples (0.00%).
DataFrame cnv - Removed 0 samples (0.00%).
Implementing feature selection using laplacian score for layer: gex with  3422 features
Calculating Laplacian scores: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3422/3422 [00:00<00:00, 9922.94it/s]
Filtering redundant features: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 513/513 [00:00<00:00, 1333.53it/s]
Implementing feature selection using laplacian score for layer: cnv with  157 features
Calculating Laplacian scores: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 157/157 [00:00<00:00, 11734.51it/s]
Filtering redundant features: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 65/65 [00:00<00:00, 10515.28it/s]

[INFO] ---------- Processing Data (test) ----------

[INFO] --------------- Cleaning Up Data ---------------
Number of NA values:  0
[INFO] DataFrame gex - Removed 0 features.
Number of NA values:  0
[INFO] DataFrame cnv - Removed 0 features.
DataFrame gex - Removed 0 samples (0.00%).
DataFrame cnv - Removed 0 samples (0.00%).

[INFO] ------------ Harmonizing Data Sets ------------

[INFO] --------------- Normalizing Data ---------------

[INFO] --------------- Normalizing Data ---------------
[INFO] Training Data Stats:
 {'feature_count in: all': 221, 'sample_count': 920}
[INFO] Test Data Stats:
 {'feature_count in: all': 221, 'sample_count': 930}
[INFO] Data import successful.
Tuning Progress:   0%|                                                                                                                                                                       | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/gnu/store/xa9b79qg2aydac3590l6x92jz3lfkw7w-flexynesis-0.1.0/bin/.flexynesis-real", line 5, in <module>
    sys.exit (mod.main ())
  File "/gnu/store/xa9b79qg2aydac3590l6x92jz3lfkw7w-flexynesis-0.1.0/lib/python3.10/site-packages/flexynesis/__main__.py", line 99, in main
    model, best_params = tuner.perform_tuning()
  File "/gnu/store/xa9b79qg2aydac3590l6x92jz3lfkw7w-flexynesis-0.1.0/lib/python3.10/site-packages/flexynesis/main.py", line 112, in perform_tuning
    suggested_params_list = opt.ask()
  File "/home/jfreige/.local/lib/python3.10/site-packages/skopt/optimizer/optimizer.py", line 367, in ask
    return self._ask()
  File "/home/jfreige/.local/lib/python3.10/site-packages/skopt/optimizer/optimizer.py", line 434, in _ask
    return self.space.rvs(random_state=self.rng)[0]
  File "/home/jfreige/.local/lib/python3.10/site-packages/skopt/space/space.py", line 900, in rvs
    columns.append(dim.rvs(n_samples=n_samples, random_state=rng))
  File "/home/jfreige/.local/lib/python3.10/site-packages/skopt/space/space.py", line 158, in rvs
    return self.inverse_transform(samples)
  File "/home/jfreige/.local/lib/python3.10/site-packages/skopt/space/space.py", line 528, in inverse_transform
    inv_transform = super(Integer, self).inverse_transform(Xt)
  File "/home/jfreige/.local/lib/python3.10/site-packages/skopt/space/space.py", line 168, in inverse_transform
    return self.transformer.inverse_transform(Xt)
  File "/home/jfreige/.local/lib/python3.10/site-packages/skopt/space/transformers.py", line 309, in inverse_transform
    X = transformer.inverse_transform(X)
  File "/home/jfreige/.local/lib/python3.10/site-packages/skopt/space/transformers.py", line 275, in inverse_transform
    return np.round(X_orig).astype(np.int)
  File "/home/jfreige/.local/lib/python3.10/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?
```

**Comment by rekado** [comment]
It's not just a problem in Flexynesis.  I can reproduce this:

```sh
$ guix shell python python-pip
[env] $ pip install numpy
[env] $ exit
$ guix shell python python-numpy -- python3 -c 'import numpy'
```

This attempts (and fails) to load numpy from ~/.local/lib.

Pending a discussion within the Guix community on how to address this, I'll change the `guix.scm` to patch the `flexynesis` script, so that Python is called with `-I`, causing it to ignore modules in ~/.local/lib.

**Comment by rekado** [comment]
For reference: https://issues.guix.gnu.org/64573

**Comment by rekado** [comment]
@jonasfreimuth could you please try again with this latest commit?

**Comment by jonasfreimuth** [comment]
Works 👍

**Comment by jonasfreimuth** [comment]
Thank you very much!

**Comment by jonasfreimuth** [comment]
Thank you very much!
