### ISSUE TITLE
error in flexynesis-cli

### ISSUE THREAD

**Issue by nilchia** [BIMSBbioinfo/flexynesis#87]
The `MultiOmicPYGDataset` class is deleted from data.py [here](https://github.com/BIMSBbioinfo/flexynesis/commit/84c31ecea1382211c1e84f492b991be18b9a41a7)

But still is imported [here](https://github.com/BIMSBbioinfo/flexynesis/blob/1d6a5660371a20bf8a855ca47fae3b866eb38123/flexynesis/cli.py#L12C51-L12C70)

This causes the [Bioconda recipe](https://github.com/bioconda/bioconda-recipes/pull/49433) to fail. 

here is the error:
```
18:12:30 BIOCONDA INFO (OUT) + flexynesis-cli --help
18:12:35 BIOCONDA INFO (OUT) Seed set to 42
18:12:42 BIOCONDA INFO (OUT) Traceback (most recent call last):
18:12:42 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/flexynesis_1722881155708/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/flexynesis-cli", line 7, in <module>
18:12:42 BIOCONDA INFO (OUT)     from flexynesis.cli import main
18:12:42 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/flexynesis_1722881155708/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.11/site-packages/flexynesis/cli.py", line 12, in <module>
18:12:42 BIOCONDA INFO (OUT)     from .data import DataImporter, MultiOmicDataset, MultiOmicPYGDataset
18:12:42 BIOCONDA INFO (OUT) ImportError: cannot import name 'MultiOmicPYGDataset' from 'flexynesis.data' (/opt/conda/conda-bld/flexynesis_1722881155708/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.11/site-packages/flexynesis/data.py)
```

**Comment by borauyar** [comment]
Thank you @nilchia . Fixed here: ffdce073727e3d2898127f0fbfc01b5d3ccaf9d4

**Comment by nilchia** [comment]
Thanks @borauyar!
Bioconda is all good now. [#49433](https://github.com/bioconda/bioconda-recipes/pull/49433)

**Comment by borauyar** [comment]
Great! Thank you very much!
